apiVersion: apps/v1
kind: Deployment
metadata:
  name: midjourney-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: midjourney-api
  template:
    metadata:
      labels:
        app: midjourney-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: midjourney-api
          image: ghcr.io/bryansmee-projects/midjourney-api@sha256:67451dbb573eadb4165103699b8f8466abaa726878ff8b162291616ddc12b14d
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: midjourney-keys
          resources:
            limits:
              cpu: "0.2"
              memory: "200Mi"
